"""Hyprland wallpaper setter backend using hyprpaper IPC with safe memory management."""

import logging
import os
from pathlib import Path
import shutil
import subprocess
import time
from typing import Optional, Tuple

from wallpaper_engine.setters.base import WallpaperSetter

logger = logging.getLogger(__name__)


class HyprlandWallpaperSetter(WallpaperSetter):
    """Wallpaper setter tailored for Hyprland desktop environment using hyprpaper.
    
    Safe Memory Architecture:
      1. Preloads the new image.
      2. Applies it across all connected monitors (",<path>").
      3. Unloads ONLY the previous image to prevent memory bloat without blanking the screen.
      4. Persists the selection into ~/.config/hypr/hyprpaper.conf with safe backups.
    """

    def __init__(self, hypr_config_dir: Optional[Path] = None) -> None:
        super().__init__()
        self.config_dir = hypr_config_dir or (Path.home() / ".config" / "hypr")
        self.conf_path = self.config_dir / "hyprpaper.conf"
        self._read_initial_active()

    @property
    def name(self) -> str:
        return "Hyprland (hyprpaper)"

    @property
    def backend_id(self) -> str:
        return "hyprland"

    def is_available(self) -> bool:
        """Check if running in Hyprland session and hyprpaper/hyprctl exist."""
        desktop = os.environ.get("XDG_CURRENT_DESKTOP", "")
        is_hyprland = "hyprland" in desktop.lower() or bool(os.environ.get("HYPRLAND_INSTANCE_SIGNATURE"))
        has_binaries = bool(shutil.which("hyprctl")) and bool(shutil.which("hyprpaper"))
        return is_hyprland and has_binaries

    def _read_initial_active(self) -> None:
        """Read the currently configured wallpaper from hyprpaper.conf if it exists."""
        if not self.conf_path.is_file():
            return
        try:
            with open(self.conf_path, "r", encoding="utf-8") as f:
                for line in f:
                    line = line.strip()
                    if line.startswith("wallpaper"):
                        parts = line.split("=", 1)
                        if len(parts) == 2:
                            val = parts[1].strip()
                            path_str = val.split(",", 1)[-1].strip()
                            p = Path(path_str)
                            if p.is_file():
                                self.active_wallpaper = p
        except Exception:
            pass

    def _ensure_hyprpaper_daemon(self) -> bool:
        """Ensure hyprpaper is running, launching it if necessary."""
        try:
            # Check if hyprpaper process is running
            res = subprocess.run(["pgrep", "-x", "hyprpaper"], capture_output=True, text=True, timeout=5)
            if res.returncode == 0:
                return True

            # If not running, launch it
            subprocess.Popen(["hyprpaper"], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
            time.sleep(0.5)  # Allow socket to bind
            return True
        except subprocess.TimeoutExpired:
            logger.warning("pgrep check timed out for hyprpaper daemon")
            return False
        except Exception as exc:
            logger.warning("Could not launch hyprpaper daemon: %s", exc)
            return False

    def _persist_config(self, image_path: Path) -> None:
        """Safely write hyprpaper.conf without destroying user customizations."""
        resolved_str = str(image_path.resolve())
        if "\n" in resolved_str or "\r" in resolved_str:
            logger.error("Rejected hyprpaper.conf path containing newline characters.")
            return

        self.config_dir.mkdir(parents=True, exist_ok=True)
        backup_path = self.config_dir / "hyprpaper.conf.bak"

        # Create initial backup if file exists and no backup was made yet
        if self.conf_path.is_file() and not backup_path.is_file():
            try:
                shutil.copy2(self.conf_path, backup_path)
            except Exception as e:
                logger.warning("Could not create hyprpaper.conf backup: %s", e)

        # Write or update configuration
        new_content = (
            f"# Generated by WallForge\n"
            f"preload = {resolved_str}\n"
            f"wallpaper = ,{resolved_str}\n"
            f"ipc = on\n"
        )

        tmp_conf = self.config_dir / "hyprpaper.conf.tmp"
        try:
            with open(tmp_conf, "w", encoding="utf-8") as f:
                f.write(new_content)
            tmp_conf.replace(self.conf_path)
        except Exception as e:
            if tmp_conf.exists():
                tmp_conf.unlink(missing_ok=True)
            logger.warning("Failed to persist hyprpaper.conf: %s", e)

    def apply_wallpaper(self, image_path: Path, mode: str = "fill") -> Tuple[bool, str]:
        """Apply wallpaper via hyprctl hyprpaper and unload only previous image."""
        path_str = str(image_path)
        if "\n" in path_str or "\r" in path_str:
            return False, "Invalid image path: newline characters are not permitted."

        if not image_path.is_file():
            return False, f"Image file not found: {image_path}"

        abs_path = str(image_path.resolve())
        if "\n" in abs_path or "\r" in abs_path:
            return False, "Invalid image path: newline characters are not permitted."

        # Ensure daemon is running
        self._ensure_hyprpaper_daemon()

        try:
            # 1. Preload new image
            res_preload = subprocess.run(
                ["hyprctl", "hyprpaper", "preload", abs_path],
                capture_output=True,
                text=True,
                check=False,
                timeout=5,
            )
            if res_preload.returncode != 0 and "already loaded" not in res_preload.stderr.lower():
                logger.warning("hyprpaper preload stderr: %s", res_preload.stderr)

            # 2. Set as wallpaper on all monitors
            res_wall = subprocess.run(
                ["hyprctl", "hyprpaper", "wallpaper", f",{abs_path}"],
                capture_output=True,
                text=True,
                check=False,
                timeout=5,
            )
            if res_wall.returncode != 0:
                return False, f"Failed to apply wallpaper: {res_wall.stderr.strip()}"

            # 3. Safely unload ONLY the superseded image (never 'unload all')
            if self.active_wallpaper and self.active_wallpaper != image_path:
                try:
                    subprocess.run(
                        ["hyprctl", "hyprpaper", "unload", str(self.active_wallpaper.resolve())],
                        capture_output=True,
                        check=False,
                        timeout=5,
                    )
                except Exception:
                    pass

            # 4. Update tracking and configuration persistence
            self.active_wallpaper = image_path
            self._persist_config(image_path)

            return True, "Successfully applied wallpaper via hyprpaper."
        except subprocess.TimeoutExpired:
            return False, "hyprctl timed out while communicating with hyprpaper daemon."
        except Exception as exc:
            return False, f"Hyprland wallpaper error: {exc}"
